In [2]:
import numpy as np

array = np.arange(9)
array2d_1 = array.reshape((3,3))
array2d_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
array2d_2 = np.arange(10,19).reshape(3,3)
array2d_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [4]:
np.concatenate((array2d_1,array2d_2), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [5]:
np.concatenate((array2d_1,array2d_2), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])