In [1]:
import numpy as np
x = np.array([
[[2, 3, 1, 0],[12, 13, 11, 10],[22, 23, 21, 20]],
[[32, 33, 31, 30],[42, 43, 41, 40],[52, 53, 51, 50]]
])
print(x)
print(x.shape)

[[[ 2  3  1  0]
  [12 13 11 10]
  [22 23 21 20]]

 [[32 33 31 30]
  [42 43 41 40]
  [52 53 51 50]]]
(2, 3, 4)


In [2]:
X = x[:, np.newaxis, 1]  # 모든 행에서 1열 값을 가져오고(행이됨), 축을 추가한다(열이됨)
print(X)
print(X.shape)

[[[12 13 11 10]]

 [[42 43 41 40]]]
(2, 1, 4)


In [3]:
X = x[:, 1, np.newaxis] # x[:, np.newaxis, 1]과 동일
print(X)
print(X.shape)

[[[12 13 11 10]]

 [[42 43 41 40]]]
(2, 1, 4)


In [4]:
X = x[1, np.newaxis, :] # 1행에서 모든 열값을 가져온다 (축추가로 열값이됨)
print(X)
print(X.shape)

[[[32 33 31 30]
  [42 43 41 40]
  [52 53 51 50]]]
(1, 3, 4)


In [5]:
X = x[1, :, np.newaxis] # 1행에서 모든 열값을 가져온다 ( 축 추가로 행값이됨 )
print(X)
print(X.shape)

[[[32 33 31 30]]

 [[42 43 41 40]]

 [[52 53 51 50]]]
(3, 1, 4)
