In [4]:
import numpy as np

arrays = [np.random.randn(3,4) for _ in range(10)]
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [5]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [6]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [7]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.stack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
np.stack((a,b), axis=-1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [10]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c.shape

(1, 3, 3)

In [11]:
np.stack(c, axis=0).shape

(1, 3, 3)

In [12]:
np.stack(c, axis=1).shape

(3, 1, 3)

In [18]:
np.stack(c, axis=2).shape
np.stack(c, axis=2)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [19]:
np.stack(c, axis=-1).shape
np.stack(c, axis=-1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])