![image.png](https://github.com/tenjumh/AI-Study/blob/master/Python%20Function%20Collection/image/numpy_array.jpg?raw=True)

In [3]:
import numpy as np

a = np.arange(1,28)
a = a.reshape(3,3,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### Axis
- axis = None : 그대로
- axis = 0 : 그냥 느껴봐. 최소단위 위치별로???
- axis = 1 : 열별로
- axis = 2 : 행별로
![image.png](https://github.com/tenjumh/AI-Study/blob/master/Python%20Function%20Collection/image/numpy_axis.JPG?raw=True)

In [20]:
print(np.sum(a, axis=None))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.sum(a, axis=2))

378
[[30 33 36]
 [39 42 45]
 [48 51 54]]
[[12 15 18]
 [39 42 45]
 [66 69 72]]
[[ 6 15 24]
 [33 42 51]
 [60 69 78]]


![image.png](https://github.com/tenjumh/AI-Study/blob/master/Python%20Function%20Collection/image/numpy_broadcast.jpg?raw=True)

In [23]:
a= np.arange(1, 25).reshape(4, 6)
b= np.arange(25, 49).reshape(4, 6)
print(a)
print()
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [24]:
print(a+100)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [28]:
A = np.arange(1, 25)
a = A.reshape((4, 6))
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


## Hsplit
![image.png](https://github.com/tenjumh/AI-Study/blob/master/Python%20Function%20Collection/image/numpy_hsplit.jpg?raw=True)
![image.png](https://github.com/tenjumh/AI-Study/blob/master/Python%20Function%20Collection/image/numpy_hsplit_2.jpg?raw=True)

In [35]:
b = np.hsplit(a, 2)
print(b)
c = np.hsplit(a, 3)
print(c)
d = np.hsplit(a,[1,3,5])
print(d)

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]]), array([[ 6],
       [12],
       [18],
       [24]])]


## Vsplit
![image.png](https://github.com/tenjumh/AI-Study/blob/master/Python%20Function%20Collection/image/numpy_vsplit.jpg?raw=True)
![image.png](https://github.com/tenjumh/AI-Study/blob/master/Python%20Function%20Collection/image/numpy_vsplit_2.jpg?raw=True)

In [37]:
e = np.vsplit(a, 2)
print(e)
f = np.vsplit(a, 4)
print(f)
g = np.vsplit(a, [1,3])
print(g)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]
