### join

In [6]:
text = ['a', 'b', 'c']
text_join = ','.join(text)
print(text_join)

a,b,c


### split

In [7]:
text_join.split(',')

['a', 'b', 'c']

In [15]:
print(text_join.split(',')[0])
print(text_join.split(',')[1])
print(text_join.split(',')[2])
# print(text_join.split(',')[3])  ==> 당연히 에러 발생

a
b
c


In [22]:
s = 'show how to index into sequences'.split()
print(s)
print(s[0])
print(s[-1])
print(s[-2])

['show', 'how', 'to', 'index', 'into', 'sequences']
show
sequences
into


### partition('기호')
- 기호를 기준으로 파티션됨
- 아래 예에서는 '-'를 기준으로 3부분으로 나뉨
- 3부분을 변수에 담아서 활용가능

In [12]:
departure, _, arrival = "Seattle-Seoul".partition('-')
print(departure)
print(arrival)
print(_)

Seattle
Seoul
-


### string함수 활용

In [16]:
"Name: {}, Age: {}".format("철수", 13)

'Name: 철수, Age: 13'

In [17]:
"Name: {0}, Age: {1}: {0}의나이가{1}".format("민호", 17)

'Name: 민호, Age: 17: 민호의나이가17'

In [18]:
a = "abcDef"
a.capitalize()

'Abcdef'

### strip : 공백 문자가 생략됨

In [19]:
s = '   abc    '
s.strip()

'abc'

### List
- [::2] : 처음부터 끝까지의 모든 원소들에 대해서 하나 걸러 하나씩
- [::3] :            "                     두개 걸러 하나씩
- [::-1] : ~역순으로 변환

In [23]:
s = 'show how to index into sequences'.split()

In [27]:
print(s)
print(s[::2])
print(s[::3])
print(s[::-1])

['show', 'how', 'to', 'index', 'into', 'sequences']
['show', 'to', 'into']
['show', 'index']
['sequences', 'into', 'index', 'to', 'how', 'show']


In [33]:
a = [[2,5]] * 3

In [34]:
print(a)
print(a[0])
print(a[0].append(8))
print(a)

[[2, 5], [2, 5], [2, 5]]
[2, 5]
None
[[2, 5, 8], [2, 5, 8], [2, 5, 8]]


### count(target) : target의 개수

In [35]:
a = [1, 5, 5, 3, 7, 0, 1, 2]

In [36]:
a.count(5)

2

### in : 리스트 안에 원소가 있는지 확인

In [37]:
"/" in ["가다/VV"]

False

In [45]:
tag_list = ["VV"]
text = ["가다/VV", "학교/NNG"]
print("/" in text)
for i in text:
    #print(i.split('/'))
    if i.split('/')[1] in tag_list:
        print(i)

False
가다/VV


### 리스트.insert(삽입 index, value)

In [48]:
a = [1,2,3]
a.insert(1,5)
print(a)

[1, 5, 2, 3]


In [49]:
a = [1,2,3]
a.extend([4,5,6])
a

[1, 2, 3, 4, 5, 6]

In [50]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

### remove : 리스트 원소 삭제

In [54]:
a = [1, 2, 3, 4, 5, 6, 7, 3, 4]
a.remove(2)
print(a)

[1, 3, 4, 5, 6, 7, 3, 4]


In [56]:
a = [1, 2, 3, 4, 5, 6, 7, 3, 4]
while 3 in a:
    a.remove(3)
print(a)

[1, 2, 4, 5, 6, 7, 4]


In [61]:
a = [1, 10, 5, 7, 6]
a.reverse()
print(a)
a.sort(reverse=True)
print(a)
a.sort()
print(a)

[6, 7, 5, 10, 1]
[10, 7, 6, 5, 1]
[1, 5, 6, 7, 10]


In [65]:
m = '나는 파이썬을 잘하고 싶다'
m = m.split()
print(m)
m.sort()  # ㄱㄴㄷ 순서
print(m)

['나는', '파이썬을', '잘하고', '싶다']
['나는', '싶다', '잘하고', '파이썬을']


### Dictionary

In [70]:
a = {'alice': [1, 2, 3], 'bob': 20, 'tony': 15, 'suzy': 30}
print(a.values())
print(a.keys())
print(a)

dict_values([[1, 2, 3], 20, 15, 30])
dict_keys(['alice', 'bob', 'tony', 'suzy'])
{'alice': [1, 2, 3], 'bob': 20, 'tony': 15, 'suzy': 30}


In [79]:
for key, val in a.items():
    print('key = {},'.format(key) + '\t' + 'value = {}'.format(val))

key = alice,	value = [1, 2, 3]
key = bob,	value = 20
key = tony,	value = 15
key = suzy,	value = 30


In [80]:
'alice' in a

True

### Set, Union, Intersection
- 집합, 합집합, 교집합

In [85]:
s = [1, 5, 1, 1, 1, 3, 7]
print('s =', s)
print('s.집합 =', set(s))

s = [1, 5, 1, 1, 1, 3, 7]
s.집합 = {1, 3, 5, 7}


In [87]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7}
c = a|b
print(c)
print(a.union(b))

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5, 6, 7}


In [88]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7}
c = a&b
print(c)
print(a.intersection(b))

{3, 4, 5}
{3, 4, 5}


In [90]:
import numpy as np
import pprint as pp
a = np.zeros((3, 4))
print(a)
pp.pprint(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
