# 벡터와 행렬 연산
<b><h2> 1. 벡터와 행렬과 텐서</h2></b>
- 벡터는 크기와 방향을 가진 양, 숫자가 나열된 형상
- 파이썬에서는 1차원 배열 또는 리스트로 표현
- 행렬은 행과 열을 가진 2차원 형상이며 파이썬에서는 2차원 배열로 표현
- 3차원부터는 텐서라고 부름

<b><h2> 2. 텐서</h2></b>

In [1]:
import numpy as np

In [2]:
# 1) 0차원 텐서 : 스칼라
d = np.array(5)
print(d.ndim)
print(d.shape)

0
()


In [3]:
# 2) 1차원 텐서 : 벡터
d = np.array([1,2,3,4])
print(d.ndim)
print(d.shape)

1
(4,)


In [4]:
# 3) 2차원 텐서 : 행렬
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d.ndim)
print(d.shape)

2
(3, 4)


In [5]:
# 4) 3차원 텐서
d=np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print(d.ndim)
print(d.shape)

3
(2, 3, 5)


- 3D 텐서는 시퀀스 데이터를 표현할 때 사용
- 시퀀스 데이터는 주로 단어의 시퀀스를 의미, 시퀀스는 문장, 문서, 뉴스 기사의 텍스트
- 3D 텐서 (samples, timesteps, word_dim) 또는 데이터를 묶는 단위인 (batch_size, timesteps, word_dim)   
* samples/batch_size : 데이터의 개수<br>
* timesteps : 시퀀스의 길이<br>
* word_dim : 단어를 표현하는 벡터의 차원<br>

- 예<br>
    - 문서1 : I like NLP<br>
    - 문서2 : I like DL<br>
    - 문서3 : DL is AI<br>
- 입력을 위해 단어를 벡터화해아함. 단어 벡터화 : 원-핫 인코딩, 워드 임베딩 방법<br>
- 여기서는 원-핫 인코딩으로 단어 벡터화<br>
I - [1 0 0 0 0 0]<br>
like - [0 1 0 0 0 0]<br>
NLP - [0 0 1 0 0 0]<br>
DL - [0 0 0 1 0 0]<br>
is - [0 0 0 0 1 0]<br>
AI - [0 0 0 0 0 1]<br>
<br>
- 예제를 입력데이터로 바꾸면, (3,3,6) 크기를 가지는 3D 텐서가 된다.<br>
[[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0]],<br>
[[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]],<br>
[[0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]]]<br>
<br>
- <b> 그 이상의 텐서</b>

![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EB%8B%A4%EC%96%91%ED%95%9C%ED%85%90%EC%84%9C%EA%B7%B8%EB%A6%BC.PNG?raw=True)

<b><h2> 3. 벡터와 행렬의 연산</h2></b>

<b>1) 벡터와 행렬의 덧셈과 뺄셈</b>

In [9]:
import numpy as np
a = np.array([8,4,5])
b = np.array([1,2,3])
print(a+b)
print(a-b)

[9 6 8]
[7 2 2]


In [10]:
import numpy as np
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print(a+b)
print(a-b)

[[15 26 37 48]
 [51 62 73 84]]
[[ 5 14 23 32]
 [49 58 67 76]]


<b>2) 벡터와 내적과 행렬의 곱셈</b>

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a,b))
print(a.shape)
print(b.shape)

32
(3,)
(3,)
()


In [19]:
import numpy as np
a = np.array([[1, 3],[2, 4]])
b = np.array([[5, 7],[6, 8]])
print(np.matmul(a,b))

[[23 31]
 [34 46]]


<b><h2> 4. 다중 선형 회귀 행렬 연산으로 이해하기</h2></b>

- 데이터의 개수가 많을 경우에는 벡터의 내적이 아니라 행렬의 곱셈으로 표현이 가능
- 다중 선형 회귀에서 데이터의 개수가 여러개일 때, 행렬의 곱셈으로 어떻게 표현할 수 있는지 예
- 집의 크기, 방의 수, 층의 수, 집이 얼마나 오래되었는지와 집의 가격이 기록된 부동산 데이터라고 가정하고 데이터를 학습하여 새로운 집의 정보가 들어왔을 때, 집가격을 예측

![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EC%A7%91%EA%B0%92%20%EC%98%88%EC%B8%A1%20%EC%98%88%EC%A0%9C.PNG?raw=True)

- 위의 데이터를 입력행렬(X)와 가중치벡터(W)의 곱으로 표현
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EC%A7%91%EA%B0%92%20%EC%98%88%EC%B8%A1%20%EC%98%88%EC%A0%9C%201.PNG?raw=True)

- 위의 표현식에 편향 벡터(B)를 더해주면 가설 수식 H(X)를 표현
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EC%A7%91%EA%B0%92%20%EC%98%88%EC%B8%A1%20%EC%98%88%EC%A0%9C%202.PNG?raw=True)
- <b><h2> H(X) = XW + B </h2></b>
- X (5X4행렬), Y (5X1행렬) 그렇다면 W는 (5X4)행렬곱(4X1)이어야 (5X1)을 얻음, 추가로 B는 (5X1)이여야 함.
- 그런데 수학적인 관례로 아래와 같은 수식으로 표현할 때, W가 입력X의 앞에 올 경우도 있어 둘다 알아야 한다.
- <b><h2> H(X) = WX + B </h2></b>
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EC%A7%91%EA%B0%92%20%EC%98%88%EC%B8%A1%20%EC%98%88%EC%A0%9C%203.PNG?raw=True)

<b><h2> 5. 샘플(Sample)과 특성(Feature)</h2></b>
- 훈련 데이터의 입력 행렬을 X라고 하였을 때 샘플(Sample)과 특성(Feature)의 정의
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EC%83%98%ED%94%8C%EA%B3%BC%20%ED%8A%B9%EC%84%B1.PNG?raw=True)
- 샘플 : 데이터를 셀 수 있는 단위로 구분
- 종속변수 y를 예측하기 위한 각각의 독립 변수 x를 특성이라고 부름

<b><h2> 6. 가중치와 편향 행렬의 크기 결정</h2></b>
- 특성을 행렬의 열로 보는 경우를 가정하여 행렬의 크기가 어떻게 결정되는지 정리
- 행렬곱은 두 가지 정의를 가지는데, 두 개의 행렬 J와 K의 곱은 다음 조건 충족
    1) 두 행렬의 곱 J x K에 대하여 행렬 J의 열의 수와 행렬 K의 행의 수 동일
    2) 두 행렬의 곱 J x K의 결과로 나온 행렬 JK의 크기는 J의 행과 K의 열의 크기
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EA%B0%80%EC%A4%91%EC%B9%98%EC%99%80%20%ED%8E%B8%ED%96%A5%ED%96%89%EB%A0%AC%EC%9D%98%20%ED%81%AC%EA%B8%B0.PNG?raw=True)
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EA%B0%80%EC%A4%91%EC%B9%98%EC%99%80%20%ED%8E%B8%ED%96%A5%ED%96%89%EB%A0%AC%EC%9D%98%20%ED%81%AC%EA%B8%B02.PNG?raw=True)
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EA%B0%80%EC%A4%91%EC%B9%98%EC%99%80%20%ED%8E%B8%ED%96%A5%ED%96%89%EB%A0%AC%EC%9D%98%20%ED%81%AC%EA%B8%B03.PNG?raw=True)
![행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EA%B0%80%EC%A4%91%EC%B9%98%EC%99%80%20%ED%8E%B8%ED%96%A5%ED%96%89%EB%A0%AC%EC%9D%98%20%ED%81%AC%EA%B8%B04.PNG?raw=True)