# 넘파이(Numpy)
- 수치 데이터를 다루는 패키지
- 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하여 선형 대수 계산
[주요 모듈]<br>
1. np.array() -리스트, 튜플, 배열로 부터 ndarray를 생성
2. np.asarray() -기존 array로 부터 ndarray를 생성
3. np.arange() -range와 비슷
4. np.linspace(start, end, num) -[start, end] 균일한 간격으로 num개 생성
5. np.logspace(start, end, num) -[start, end] log scale 간격으로 num개 생성

In [3]:
import numpy as np
np.__version__

'1.17.2'

# 1. np.array()</br>

In [8]:
a = np.array([1,2,3,4,5])
print(type(a))
print(a)
print(a.ndim)
print(a.shape)    #크기 5의 배열 (5,)

<class 'numpy.ndarray'>
[1 2 3 4 5]
1
(5,)


In [7]:
b = np.array([[10,20,30], [60,70,80]])
print(b)
print(b.ndim)   #차원출력
print(b.shape)   #형상출력

[[10 20 30]
 [60 70 80]]
2
(2, 3)


In [15]:
#ndarray 초기화
a = np.zeros((2,3))
print(a)
b = np.ones((2,3))
print(b)
c = np.full((2,3), 7)   #상수 7로 배열 생성
print(c)
d = np.eye(3)    #대각선으로는 1이고 나머지는 0인 배열
print(d)
e = np.random.random((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.71682524 0.9128714  0.28299504]
 [0.09021624 0.06983259 0.63496685]]


# 2. np.arange()
- 지정해준 범위에 대해서 배열을 생성
- numpy.arange(start, stop, step, dtype)<br>
a = np.arange(n) # 0, ..., n-1까지 범위의 지정<br>
a = np.arange(i, j, k) # i부터 j-1까지 k씩 증가하는 배열.

In [16]:
a = np.arange(10)
print(a)
b = np.arange(1, 10, 2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [17]:
#reshape()
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [27]:
#Numpy 슬라이싱
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("-------------")
b = a[0:2, 0:2]
print(b)
print("----1행의 모든 열---------")
c = a[0, :]
print(c)
print("----행 상관없이 두번째 열출력-------")
d = a[:, 1]
print(d)

[[1 2 3]
 [4 5 6]]
-------------
[[1 2]
 [4 5]]
----1행의 모든 열---------
[1 2 3]
----행 상관없이 두번째 열출력-------
[2 5]


In [30]:
#Numpy 정수 인덱싱
a = np.array([[1,2],[4,5],[7,8]])
print(a)
print("--------------")
b = a[[2,1],[1,0]]    #a[[행2, 열1], [행1, 열0]]
print(b)

[[1 2]
 [4 5]
 [7 8]]
--------------
[8 4]


In [39]:
#Numpy 연산
#+, -, *, /의 연산자를 사용
#add(), subtract(), multiply(), divide() 함수를 사용
x = np.array([1,2,3])
y = np.array([4,5,6])
b = x + y
c = np.add(x, y)
print(b, c)
print("---------------")
d = x - y
e = np.subtract(x, y)
print(d, e)
print("---------------")
f = x * y
g = np.multiply(x, y)
print(f, g)
print("---------------")
h = x / y
i = np.divide(x, y)
print(h, i)

[5 7 9] [5 7 9]
---------------
[-3 -3 -3] [-3 -3 -3]
---------------
[ 4 10 18] [ 4 10 18]
---------------
[0.25 0.4  0.5 ] [0.25 0.4  0.5 ]


In [44]:
#***행렬 곱
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(a, b)
print(c)
print("-----행렬곱과 곱은 다르죠?-------")
d = a*b
print(d)

[[19 22]
 [43 50]]
-----행렬곱과 곱은 다르죠?-------
[[ 5 12]
 [21 32]]
