# 1. 지도 학습(Supervised Learning)
<br>
<훈련 데이터><br>
X_train : 문제지 데이터<br>
y_train : 문제지에 대한 정답 데이터.<br>
<br>
<테스트 데이터><br>
X_test : 시험지 데이터.<br>
y_test : 시험지에 대한 정답 데이터.<br>

# 2. X와 y분리하기
<b>1) zip함수를 이용하여 분리하기</b><br>
- zip()함수는 동일한 개수를 가지는 시퀸스 자료형에서 각 순서에 등장하는 원소들끼리 묶어주는 역할
- zip()함수 실습

In [31]:
X, y = zip(['a', 1], ['b', 2], ['c', 3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


zip()함수를 통해 첫번째 원소들끼리, 두번째 원소들끼리 묶임

In [32]:
sequences = [['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)    # *를 추가
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


<b>2) 데이터프레임을 이용하여 분리하기</b><br>

In [33]:
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일본문', '스팸메일유무']

df = pd.DataFrame(values, columns = columns)
df

메일본문  스팸메일유무
0        당신에게 드리는 마지막 혜택!       1
1    내일 뵐 수 있을지 확인 부탁드...       0
2    도연씨. 잘 지내시죠? 오랜만입...       0
3  (광고) AI로 주가를 예측할 수 있다!       1

In [34]:
X = df['메일본문']
y = df['스팸메일유무']

In [35]:
print(X)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일본문, dtype: object


In [36]:
print(y)

0    1
1    0
2    0
3    1
Name: 스팸메일유무, dtype: int64


<b>3) Numpy를 이용하여 분리하기</b><br>

In [37]:
import numpy as np
ar = np.arange(0, 16).reshape((4,4))
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
X = ar[:,:3]
y = ar[:,-1]

In [39]:
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [40]:
print(y)

[ 3  7 11 15]


# 3. 테스트 데이터 분리하기
<b>1) 사이킷 런을 이용하여 분리하기</b><br>
- train_test_split()

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1234)

In [42]:
X_train

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [43]:
y_train

array([ 7, 11, 15])

In [44]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)

In [47]:
print(X)
print(list(y)) #레이블 데이터

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)

In [49]:
print(X_train)
print(X_test)

[[2 3]
 [4 5]
 [6 7]]
[[8 9]
 [0 1]]


<b>2) 수동으로 분리하기</b><br>

In [51]:
import numpy as np
X, y = np.arange(0,24).reshape((12,2)), range(12)

In [53]:
print(X)
print(list(y))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [56]:
n_of_train = int(len(X) * 0.8)
n_of_test = int(len(X) - n_of_train)
print(n_of_train)
print(n_of_test)

9
3


n_of_train을 len(X) * 0.8로 구했듯이 n_of_test 또한 len(X) * 0.2로 계산하면 안됨<br>
어느 한 쪽을 먼저 계산하고 그 값만큼 제외하는 방식으로 계산

In [57]:
X_test = X[n_of_train:] #전체 데이터 중에서 20%만큼 뒤의 데이터 저장
y_test = y[n_of_train:] #전체 데이터 중에서 20%만큼 뒤의 데이터 저장
X_train = X[:n_of_train] #전체 데이터 중에서 80%만큼 앞의 데이터 저장
y_train = y[:n_of_train] #전체 데이터 중에서 80%만큼 앞의 데이터 저장