# 토픽 모델링(Topic Modeling)
- 한국어로 주제라고 하며 텍스트 본문의 숨겨진 의미 구조를 발견하기 위해 사용되는 텍스트 마이닝 기법(문서 집합의 추상적인 주제를 발견)

# 1) 잠재 의미 분석(Latent Semantic Analysis, LSA)
- 토픽 모델링이라는 분야에 아이디어를 제공한 알고리즘.
- LDA : LSA의 단점을 개선하여 탄생한 알고리즘으로 토픽 모델리에 보다 적합한 알고리즘
- BoW에 기반한 DTM이나 TF-IDF는 단어의 빈도 수를 이용한 수치화 방법이기에 단어의 의미 고려하지 못하는 단점.
- DTM의 잠재된(latent)의미를 이끌어내는 방법으로 LSA라는 방법 사용
- 선형대수학의 특이값 분해9Singular Value Decomposition, SVD)를 이해 필요

(1)특이값 분해(Singular Value Decomposition, SVD)
-SVD란 A가 m x n 행렬일 때, 다음과 같이 3개의 행렬의 곱으로 분해하는 것
![유클리드거리](https://github.com/tenjumh/GraduateSchool/blob/master/Study/Linear%20Algebra_%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%ED%95%99/image/1.%20%EC%BA%A1%EC%B2%98.PNG?raw=True)
-직교행렬이란 자신과 자신의 전치행렬의 곱 또는 이를 반대로 곱한 결과가 단위행렬이 되는 행렬<br>
-대각행렬이란 주대각선을 제외한 곳의 원소가 모두 0인 행렬을 의미<br>
-SVD로 나온 대각 행렬의 대각 원소의 값을 행렬 A의 특이값

1) 전치행렬(Transposed Matrix)<br>
전치행렬은 원래의 행렬에서 행과 열을 바꾼 행렬<br>
즉, 주대각선을 축으로 반사 대칭하여 얻는 행렬<br>
M = [[1, 2], [3, 4], [5, 6]]  (3x2행렬)<br>
M^T = [[1, 3, 5], [2, 4, 6]]  (2x3행렬)<br>

2) 단위행렬(Identity Matrix)<br>
주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각행렬<br>
I라고도 함<br>

3) 역행렬(Inverse Matrix)<br>
행렬 A와 어떤 행렬을 곱했을 때, 결과로 단위 행렬이 나온다면 이를 A의 역행렬이라고 하며 A^-1이라고 표현
![역행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EC%97%AD%ED%96%89%EB%A0%AC.PNG?raw=True)

4) 직교행렬(Orthogonal Matrix)<br>
n x n 행렬 A에 대해서 A x A^T = I를 만족하면서 A^T x A = I를 만족하는 행렬 A를 직교행렬이라고 한다.<br>
결국, A^-1 = A^T를 만족한다.

5) 대각행렬(Diagonal Matrix)<br>
주대각선을 제외한 곳의 원소가 모두 0인 행렬, 이때 주대각선 원소를 a라고 표현
![대각행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EB%8C%80%EA%B0%81%ED%96%89%EB%A0%AC.PNG?raw=True)
-m x n행렬일 때, m > n인 경우
![대각행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EB%8C%80%EA%B0%81%ED%96%89%EB%A0%AC2.PNG?raw=True)
-m x n행렬일 때, m < n인 경우
![대각행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EB%8C%80%EA%B0%81%ED%96%89%EB%A0%AC3.PNG?raw=True)

SVD를 통해 나온 대각 행렬"시그마"는 추가적인 성질을 가지는데, 대각행렬 "시그마"의 주대각원소를 행렬 A의 특이값이라 함, 내림차순으로 정렬되는 특징이 있음
예를 들어 특이값 12.4, 9.5, 1.3이 내림차순으로 정렬되어져 있는 모습
![대각행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/%EB%8C%80%EA%B0%81%ED%96%89%EB%A0%AC4.PNG?raw=True)

(2) 절단된 SVD(Truncated SVD)
지금까지 설명한 SVD는 Full SVD이며 LSA 경우 Full SVD에서 나온 3개의 행렬에서 일부 벡터들을 삭제시킨 Truncated SVD(절단된 SVD)를 사용
![SVD](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/SVD_full.PNG?raw=True)

![Truncated SVD](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/SVD_thin_compact_truncated.PNG?raw=True)
절단된 SVD는 대각행렬 "시그마"의 대각 원소의 값 중에서 상위값 t개만 남게된다. 절단된 SVD를 수행하면 값의 손실이 일어나므로 기존의 행렬 A를 복구 불가.<br>
또한 U행렬과 V행렬의 t열까지만 남기고 t는 우리가 찾고자하는 토픽의 수를 반영한 하이퍼파라미터값임.<br>
하이퍼파라미터란 사용자가 직접 값을 선택하며 선능에 영향을 주는 매개변수로 t를 선택하는 것은 쉽지 않음<br>
주대각행렬("시그마")는 내림차순으로 구성되어 있기 때문에 밑으로 갈수록 중요도가 낮아짐 따라서 t를 크게 잡으면 다양한 의미를 포함하며 t를 작게 잡으면 노이즈를 제거<br>
일부 벡터를 삭제하는 것은<br> (1)데이터의 차원을 줄인다고도 하는데 계산량도 낮아지는 효과<br> (2)중요하지 않은 정보 삭제 효과<br> (3)즉 설명력이 높은 정보만 남음<br> --> 기존 행렬에서는 드러나지 않았던 심층적인 의미 확인

(3) 잠재 의미 분석(Latent Semantic Analysis, LSA)
- 기존 DTM이나 DTM에 단어의 중요도에 따른 가중치를 주었던 TF-IDF행렬은 단어의 의미를 전혀 고려하지 못한다는 단점을 갖고 있었다.
- LSA는 기본적으로 DTM이나 TF-IDF행렬에 절단된 SVD를 사용하여 차원을 축소, 단어들의 잠재적인 의미를 끌어낸다는 아이디어임
![대각행렬](https://github.com/tenjumh/GraduateSchool/blob/master/Study/NLP_Natural%20Language%20Processing/image/LSA%20%EC%98%88%EC%8B%9C.PNG?raw=True)

위와 같은 DTM을 실제로 파이썬을 통해 만들면

In [3]:
import numpy as np
A = np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
np.shape(A)

(4, 9)

# Full SVD

-4 x 9 DMT생성<br>
-Full SVD를 수행<br>
-"시그마"를 S, V^T를 VT

In [4]:
U, s, VT = np.linalg.svd(A, full_matrices = True)

In [5]:
print(U.round(2))   #두번째 자리까지만 출력하기위해서 .round(2)를 사용
np.shape(U)

[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]


(4, 4)

In [6]:
print(s.round(2))
np.shape(s)

[2.69 2.05 1.73 0.77]


(4,)

-Numpy의 linalg.svd()는 특이값 분해의 결과로 대각 행렬이 아니라 특이값의 리스트를 반환한다. 그러므로 다시 대각 행렬로 바꿔 줘야함.<br>
우선 특이값을 s에 저장하고 대각행렬 크기의 행렬을 생성한 후 그 행렬에 특이값을 삽입

In [7]:
S = np.zeros((4, 9)) # 대각 행렬의 크기인 4 x 9의 임의의 행렬 생성
S[:4, :4] = np.diag(s) # 특이값을 대각행렬에 삽입
print(S.round(2))
np.shape(S)

[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


(4, 9)

대각행렬 S가 내림차순으로 구성된 것을 볼수 있음

In [8]:
print(VT.round(2))
np.shape(VT)

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


(9, 9)

U x S x VT를 하면 기존 행렬 A가 나와야 함.<br>
Numpy의 allclose()는 2개의 행렬이 동일하면 True를 리턴

In [9]:
np.allclose(A, np.dot(np.dot(U,S),VT).round(2))

True

# Truncated SVD
- t=2

In [10]:
S=S[:2,:2]   #기존 4 x 9  대각행렬 중 2 x 2만 취함
print(S.round(2))

[[2.69 0.  ]
 [0.   2.05]]


In [11]:
# 직교 행렬 U에 대해서도 2개의 열만 남기고 제거
U=U[:,:2]
print(U.round(2))

[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [12]:
# 행렬 V의 전치 행렬인 VT에 대해서 2개의 행만 남김
VT=VT[:2,:]
print(VT.round(2))

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


축소된 행렬 U, S, VT에 대해서 U x S x VT연산을 하면 기존 A와 다른 결과가 나옴

In [13]:
A_prime=np.dot(np.dot(U,S), VT)
print(A)
print(A_prime.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]


대체적으로 기존에 0인 값들은 0에 가까운 값<br>
1인 값들은 1에 가까운 값이 나옴<br>
또한 값이 제대로 복구되지 않은 구간도 존재함.<br>
축소된 U, S, VT의 크기가 어떤 의미인지 확인

-축소된 U는 4 x 2크기를 가지는데 --> 문서의 개수 x 토픽의 수 t의 크기임.<br>
-단어의 개수인 9는 유지되지 않는데 문서의 개수인 4의 크기가 유지되었으니 4개의 문서 각각을 2개의 값으로 표현하고 있음<br>

# 실습
- 사이킷런에서 Twenty Newsgroups라고 불리는 20개의 다른 주제를 가진 뉴스 데이터 제공
- LSA를 사용 문서의 수를 원하는 토픽의 수로 압축한 뒤에 각 토픽당 가장 중요한 단어 5개를 출력

1) 뉴스 데이터에 대한 이해

In [1]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers','footeers','quotes'))
documents = dataset.data
len(documents)

11314

In [2]:
#first News
documents[1]

'\n\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can\'t pity you, Jim.  And I\'m sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won\'t be bummin\' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don\'t forget your Flintstone\'s Chewables!  :) \n--\nBake Timmons, III\n\n-- "...there\'s nothing higher, stronger, more wholesome and more useful in life\nthan some good memory..." -- Alyosha in Brothers Karamazov (Dostoevsky)\n'

In [3]:
# 사이킷런에서 제공하는 이 뉴스 데이터가 어떤 20개의 카테고리를 갖는지 확인가능
print(dataset.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


2) 텍스트 전처리
- 알파벳을 제외한 구두점, 숫자, 특수문자 제거
- 짧은 단어 제거
- 모든 문자 -> 소문자 변경

In [4]:
news_df = pd.DataFrame({'document':documents})
# 특수 문자 제거
news_df['clean_doc'] = news_df['document'].str.replace("[^a-zA-Z]"," ")
# 길이가 3이하인 단어 제거
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: x.lower())

In [5]:
news_df['clean_doc'][1]

'yeah expect people read actually accept hard atheism need little leap faith jimmy your logic runs steam sorry pity sorry that have these feelings denial about faith need well just pretend that will happily ever after anyway maybe start newsgroup atheist hard bummin much forget your flintstone chewables bake timmons there nothing higher stronger more wholesome more useful life than some good memory alyosha brothers karamazov dostoevsky'

- 불용어 제거 (먼저 토큰화 진행 후 불용어 제거)

In [7]:
from nltk.corpus import stopwords
# NLTK로부터 불용어 받아옴
stop_words = stopwords.words('english')
# 토큰화
tokenized_doc = news_df['clean_doc'].apply(lambda x: x.split())
# 불용어 제거
tokenized_doc = tokenized_doc.apply(lambda x: [item for item in x if item not in stop_words])

In [8]:
print(tokenized_doc[1])

['yeah', 'expect', 'people', 'read', 'actually', 'accept', 'hard', 'atheism', 'need', 'little', 'leap', 'faith', 'jimmy', 'logic', 'runs', 'steam', 'sorry', 'pity', 'sorry', 'feelings', 'denial', 'faith', 'need', 'well', 'pretend', 'happily', 'ever', 'anyway', 'maybe', 'start', 'newsgroup', 'atheist', 'hard', 'bummin', 'much', 'forget', 'flintstone', 'chewables', 'bake', 'timmons', 'nothing', 'higher', 'stronger', 'wholesome', 'useful', 'life', 'good', 'memory', 'alyosha', 'brothers', 'karamazov', 'dostoevsky']


- 불용어인 your, about, just, that, will, after 등이 사라지고 토큰화 됨

3) TF-IDF 행렬 만들기
- 불용어 제거를 위해 토큰화를 수행했지만
- TfidVectorizer(TF-IDF참고)는 기본적으로 토큰화가 되어있지 않은 텍스트 데이터를 입력으로 사용
- 토근화 작업을 역으로 취소하는 작업 수행 (역토큰화)

In [11]:
# 역토큰화 (토큰화 작업을 역으로 되돌림)
detokenized_doc = []
for i in range(len(news_df)):
    t = ' '.join(tokenized_doc[i])
    detokenized_doc.append(t)

news_df['clean_doc'] = detokenized_doc

In [12]:
news_df['clean_doc'][1]

'yeah expect people read actually accept hard atheism need little leap faith jimmy logic runs steam sorry pity sorry feelings denial faith need well pretend happily ever anyway maybe start newsgroup atheist hard bummin much forget flintstone chewables bake timmons nothing higher stronger wholesome useful life good memory alyosha brothers karamazov dostoevsky'

In [16]:
# 1000개에 대한 TF-IDF행렬 수행
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english',
                           max_features = 1000,
                           max_df = 0.5,
                           smooth_idf=True)

X = vectorizer.fit_transform(news_df['clean_doc'])
X.shape

(11314, 1000)

4) 토픽 모델링(Topic Modeling)
- TF-IDF 행렬을 다수의 행렬로 분해
- 사이킷런의 "절단된 SVD(Truncated SVD) 사용 : 차원 축수
- 기존 뉴스 데이터가 20개의 카테고리를 갖고 있었기에 이를 가정하에 진행

In [17]:
from sklearn.decomposition import TruncatedSVD
svd_model = TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)
svd_model.fit(X)
len(svd_model.components_)

20

- svd_model.components_는 LSA에서 VT에 해당

In [19]:
#import numpy as np
np.shape(svd_model.components_)

(20, 1000)

- 20 X 1000 : 토픽의 수(t) X 단어의 수의 크기

In [20]:
terms = vectorizer.get_feature_names()  #단어 집합. 1000개의 단어가 저장됨

def get_topics(components, feature_names, n =5):
    for idx, topic in enumerate(components):
        print("Topic %d:" %(idx+1), [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(svd_model.components_, terms)

Topic 1: [('like', 0.20505), ('know', 0.18838), ('people', 0.18376), ('think', 0.16767), ('good', 0.14274)]
Topic 2: [('thanks', 0.3379), ('windows', 0.27465), ('mail', 0.17725), ('card', 0.17113), ('drive', 0.15578)]
Topic 3: [('game', 0.38223), ('team', 0.32242), ('year', 0.27387), ('games', 0.24544), ('season', 0.18665)]
Topic 4: [('drive', 0.51326), ('scsi', 0.20344), ('disk', 0.15638), ('hard', 0.15618), ('card', 0.15153)]
Topic 5: [('thanks', 0.37204), ('drive', 0.3638), ('know', 0.25132), ('scsi', 0.13857), ('advance', 0.12312)]
Topic 6: [('windows', 0.34853), ('know', 0.23487), ('like', 0.1898), ('think', 0.17901), ('file', 0.12958)]
Topic 7: [('like', 0.55178), ('bike', 0.1782), ('know', 0.17522), ('chip', 0.11768), ('sounds', 0.079)]
Topic 8: [('know', 0.24374), ('thanks', 0.22401), ('government', 0.21558), ('people', 0.18357), ('israel', 0.12575)]
Topic 9: [('card', 0.51616), ('video', 0.2482), ('monitor', 0.15725), ('sale', 0.15), ('drivers', 0.13072)]
Topic 10: [('like', 0